# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - olliestyle1989@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
